

export const metadata = {
  title: "APIXcel a web solution",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <>
      {children}
    </>
  );
}
