import Image from "next/image";
import { navigationItems } from "../../../public/Data/NavigationData";
import Link from "next/link";

export const metadata = {
  title: "APIXcel a web solution",
  description: "Generated by create next app",
};

export default function PublicLayout({ children }) {
  return (
    <div className="container">
      <ul className="dashboard_left">
        {navigationItems.map(({ id, label, url, iconUrl }) => (
          <li key={id}>
            <Link href={url} className="nav_item">
              <Image width={18} height={18} src={iconUrl} alt="" /> {label}
            </Link>
          </li>
        ))}
      </ul>
      <div className="dashboard_right">{children}</div>
    </div>
  );
}
